//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirQualityVisualisation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirData_F2019Entities3 : DbContext
    {
        public AirData_F2019Entities3()
            : base("name=AirData_F2019Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aktivitet_Table> Aktivitet_Table { get; set; }
        public virtual DbSet<AnalyseResultat_Table> AnalyseResultat_Table { get; set; }
        public virtual DbSet<DataType_Table> DataType_Table { get; set; }
        public virtual DbSet<Geometri_Table> Geometri_Table { get; set; }
        public virtual DbSet<Instrument_Table> Instrument_Table { get; set; }
        public virtual DbSet<Maalested_Table> Maalested_Table { get; set; }
        public virtual DbSet<Measurement_Table> Measurement_Table { get; set; }
        public virtual DbSet<Opstilling_Table> Opstilling_Table { get; set; }
        public virtual DbSet<Product_Table> Product_Table { get; set; }
        public virtual DbSet<ProductType_Table> ProductType_Table { get; set; }
        public virtual DbSet<Proeve_Table> Proeve_Table { get; set; }
        public virtual DbSet<Stof_Table> Stof_Table { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Unit_Table> Unit_Table { get; set; }
        public virtual DbSet<Final_View> Final_View { get; set; }
    }
}
