//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirQualityVisualisation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aktivitet_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aktivitet_Table()
        {
            this.Product_Table = new HashSet<Product_Table>();
        }
    
        public int AktivitetId { get; set; }
        public Nullable<int> AktivitetTypeId { get; set; }
        public Nullable<int> OpstillingId { get; set; }
        public Nullable<System.DateTime> DatoMaerke { get; set; }
        public Nullable<int> ExpPeriodeTypeId { get; set; }
    
        public virtual Opstilling_Table Opstilling_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Table> Product_Table { get; set; }
    }
}
