//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirQualityVisualisation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalyseResultat_Table
    {
        public int AnalyseResultatId { get; set; }
        public int StofId { get; set; }
        public int AnalyseInstruksId { get; set; }
        public int DataTypeId { get; set; }
        public Nullable<double> RaaResultat { get; set; }
        public int RaaEnhedId { get; set; }
        public Nullable<double> ProjektResultat { get; set; }
        public Nullable<int> ProjektEnhedId { get; set; }
        public Nullable<System.DateTime> AnalyseDato { get; set; }
        public int ProduktId { get; set; }
    
        public virtual Stof_Table Stof_Table { get; set; }
        public virtual Unit_Table Unit_Table { get; set; }
    }
}
