//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirQualityVisualisation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Final_View
    {
        public Nullable<System.DateTime> DatoMaerke { get; set; }
        public string Navn { get; set; }
        public int ProduktId { get; set; }
        public Nullable<double> RaaResultat { get; set; }
        public string Kode { get; set; }
        public string StofNavn { get; set; }
        public string Expr1 { get; set; }
    }
}
