//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirQualityVisualisation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opstilling_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Opstilling_Table()
        {
            this.Aktivitet_Table = new HashSet<Aktivitet_Table>();
        }
    
        public int OpstillingId { get; set; }
        public string Kode { get; set; }
        public Nullable<int> MaaleStedId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aktivitet_Table> Aktivitet_Table { get; set; }
        public virtual Maalested_Table Maalested_Table { get; set; }
    }
}
