//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirQualityVisualisation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Table
    {
        public int ProduktId { get; set; }
        public Nullable<int> AktivitetId { get; set; }
        public Nullable<int> ProduktTypeId { get; set; }
    
        public virtual Aktivitet_Table Aktivitet_Table { get; set; }
        public virtual Measurement_Table Measurement_Table { get; set; }
        public virtual ProductType_Table ProductType_Table { get; set; }
        public virtual Proeve_Table Proeve_Table { get; set; }
    }
}
