//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirQualityVisualisation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proeve_Table
    {
        public int ProduktId { get; set; }
        public Nullable<int> ProeveTypeId { get; set; }
        public Nullable<int> AnalyseTypeId { get; set; }
    
        public virtual Product_Table Product_Table { get; set; }
    }
}
